# general info
title: My-Lab
owner: Shuami Labs
email: shuamilabs@gmail.com
description: A simple blogging theme
baseurl: ""
url: ""
encoding: utf-8
language: en
theme: my-lab

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'

pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
  title: 'Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# socmed
twitter_username:
github_username: shuamilabs
instagram_username: shuamilabs
facebook_username: shuamilabs
youtube_username: UC1CaCMwJq3qd0I1yOf4uO8Q
disqus_username: 

# navigation
permalink: pretty # /:year/:month/:day/:title/
excerpt_separator: <!-- more -->

# assets
sass:
  sass_dir: _sass
  style: compressed

# plugins
plugins:
  - jekyll-paginate-v2
  
exclude:
  - Gemfile
  - Gemfile.lock